/**
 * Created by LinYong on 2016/3/29.
 */

export const TICKET_INFO='TICKET_INFO';
export const TICKET_INIT='TICKET_INIT';
export const TICKET_CREATE='TICKET_CREATE';
export const TICKET_STORE='TICKET_STORE';
export const TICKET_CREATE_ERROR='TICKET_CREATE_ERROR';
export const TICKET_SAVING='TICKET_SAVING';
export const TICKET_SAVE_DONE='TICKET_SAVE_DONE';
export const TICKET_SAVE_RESET='TICKET_SAVE_RESET';


export const TICKET_INIT_CUSTOMER='TICKET_INIT_CUSTOMER';
export const TICKET_STORE_CUSTOMER='TICKET_STORE_CUSTOMER';
export const TICKET_INIT_CUSTOMER_DOING='TICKET_INIT_CUSTOMER_DOING';
export const TICKET_INIT_CUSTOMER_DONE='TICKET_INIT_CUSTOMER_DONE';
export const TICKET_INIT_CUSTOMER_ERROR='TICKET_INIT_CUSTOMER_ERROR';
export const TICKET_EDIT_CUSTOMER='TICKET_EDIT_CUSTOMER';
export const TICKET_EDITTING_CUSTOMER='TICKET_EDITTING_CUSTOMER';
export const TICKET_EDIT_CUSTOMER_DONE='TICKET_EDIT_CUSTOMER_DONE';
export const TICKET_EDIT_CUSTOMER_ERROR='TICKET_EDIT_CUSTOMER_ERROR';
export const TICKET_EDIT_CUSTOMER_RESET='TICKET_EDIT_CUSTOMER_RESET';


export const TICKET_INIT_SELECT_OPTIONS='TICKET_INIT_SELECT_OPTIONS';
