/**
 * Created by linyong on 16/3/18.
 */
/*
 * action 类型
 */
export const CUSTOMER_SEARCH = 'CUSTOMER_SEARCH';
export const CUSTOMER_SEARCH_CREATE = 'CUSTOMER_SEARCH_CREATE';
export const CUSTOMER_SEARCH_SELECTED = 'CUSTOMER_SEARCH_SELECTED';
export const CUSTOMER_SEARCH_KEY = 'CUSTOMER_SEARCH_KEY';
export const CUSTOMER_CREATE = 'CUSTOMER_CREATE';
export const CUSTOMER_EDIT = 'CUSTOMER_EDIT';
export const CUSTOMER_SAVING = 'CUSTOMER_SAVING';
export const CUSTOMER_SAVE_DONE = 'CUSTOMER_SAVE_DONE';
export const CUSTOMER_SAVE_ERROR = 'CUSTOMER_SAVE_ERROR';
export const  CUSTOMER_SAVE_RESET = 'CUSTOMER_SAVE_RESET';
